### ISSUE TITLE
Unavailable API handle

### ISSUE THREAD

**Issue by drabaly** [righettod/website-passive-reconnaissance#28]
It would be nice to handle unavailable APIs, so it does not crash the tool

**Comment by righettod** [comment]
you have right, it's a topic that I have forgotten 👎

**Comment by righettod** [comment]
https://stackoverflow.com/questions/16511337/correct-way-to-try-except-using-python-requests-module

**Comment by righettod** [comment]
The error handling is now on IRL testing phase 😃
