### ISSUE TITLE
Adding a dorks search to the ones already performed

### ISSUE THREAD

**Issue by drabaly** [righettod/website-passive-reconnaissance#89]
It would be worth (rarely ,but still) to add a dork query related to this Twitter post: https://twitter.com/TakSec/status/1644008962524856321

This would highlight part of applications that require some focus.

**Comment by righettod** [comment]
Implemented 😃 

![image](https://user-images.githubusercontent.com/1573775/230778700-a7b1a5de-c9b9-47e2-98d6-dc649fbd75c2.png)
